checks:
  php:
    code_rating: true
    duplication: true
    use_self_instead_of_fqcn: true
    uppercase_constants: true
    simplify_boolean_return: true
    return_doc_comments: true
    return_doc_comment_if_not_inferrable: true
    phpunit_assertions: true
    parameter_doc_comments: true
    no_short_method_names:
        minimum: '3'
    line_length:
        max_length: '120'
    function_in_camel_caps: true
    encourage_single_quotes: true

filter:
  excluded_paths:
    - 'tests/*'