---
Name: firesphere-jwt-injections
After: "#coresecurity"
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Security\AuthenticationHandler:
    properties:
      Handlers:
        jwt: '%$Firesphere\GraphQLJWT\Authentication\JWTAuthenticationHandler'
  Firesphere\GraphQLJWT\Authentication\JWTAuthenticationHandler:
    properties:
      JWTAuthenticator: '%$Firesphere\GraphQLJWT\Authentication\JWTAuthenticator'
  SilverStripe\Security\Security:
    properties:
      Authenticators:
        default: '%$Firesphere\GraphQLJWT\Extensions\ExtendedMemberAuthenticator'
Firesphere\GraphQLJWT\Extensions\MemberExtension:
  requires_user_activation: true

---
Name: firesphere-jwt-middleware
After: "#session-manager-middleware"
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Control\Director:
    properties:
      Middlewares:
        LoginSessionMiddleware: '%$Firesphere\GraphQLJWT\Middleware\JWTLoginSessionMiddleware'