---
after: graphqlconfig
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Security\AuthenticationHandler:
    class: SilverStripe\Security\RequestAuthenticationHandler
    properties:
      Handlers:
         jwt: %$Firesphere\GraphQLJWT\JWTAuthenticationHandler
  Firesphere\GraphQLJWT\JWTAuthenticationHandler:
    properties:
      Authenticator: %$Firesphere\GraphQLJWT\JWTAuthenticator
---
after: graphqlroutes
---
SilverStripe\Control\Director:
  rules:
    graphql:
      Controller: 'SilverStripe\GraphQL\Controller'
      # @internal - Experimental config
      # @todo - move this to a per-schema configuration, and simply register the named schema for this endpoint
      # https://github.com/silverstripe/silverstripe-graphql/issues/52
      Stage: Live
      Permissions: false
---
name: graphqljwt
---
Firesphere\GraphQLJWT\JWTAuthenticator:
  prefix: 'jwt_'
  nbf_time: 60
  nbf_expiration: 3600
  signer_key: 'SilverStripe_jwt'
  anonymous_allowed: true